### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by YotamGit** [YotamGit/tilde#2]
- [ ] replace URL and keywords with my own
- [ ] change suggestions
- [ ] remove unneeded commands/add new ones

style
- [ ] redesign the homepage
- [ ] change clock style and add date with format "08 AUG 2021"
- [ ] change search bar style
- [ ] add logos (maybe)
